### ISSUE TITLE
Using MCP2515 as CAN interface

### ISSUE THREAD

**Issue by s-hemer** [macchina/m2-hardware#4]
After receiving my Macchina Interface-only board I backed in the Kickstarter campaign, I am a little disappointed that I cannot switch the MCP2515 to use it for SWCAN or standard CAN. I am no expert in SWCAN but wouldn't it be possible to just switch the transceiver via some jumpers to one of the two transceivers that are used with the SAM-internal CAN controllers?

(This relates also to the forum entry https://forum.macchina.cc/t/raspberry-pi-wiring-and-libraries/260/7)

Regards

Steffen

**Comment by redheadedrod** [comment]
You are likely to get a better response on the forum.

**Comment by adamvoss** [comment]
> You are likely to get a better response on the forum.

I agree so am closing this.  @s-hemer please start a discussion on the forum.

**Comment by s-hemer** [comment]
This is in my opinion a deficit of the board that might be changed in a future version ??!! So it should be discussed here as an issue. That's what it is for, the issue tracker. For the forum, I would need another damn login and there people may discuss things like "How do I use this and that".
Maybe you provide the real sources as mentioned in the other issue then I can check on my own what is possible and what not.
Thanks for the support.

**Comment by adamvoss** [comment]
I am sorry for your frustration, I would like to see you get a response to your request, which is why both both redheadedrod and I directed you to the forum; because that is where the people who are likely to respond will read.

Regarding the original post, I perhaps missed that it was supposed to be a change request for future iterations of the board.  I saw it as a question of whether it would be possible to switch the transceiver using jumpers and the audience that will answer usage questions is at the forum.

**Comment by redheadedrod** [comment]
Git issues generally are on a specific software piece that can be dealt with. Future plans and that sort of thing should be discussed on the forum. Yes it requires another account but those serious about using this stuff shouldn't have an issue there. The issue with issues or comments here is that they will be missed in the future. At least on the forum it will come up in searches much easier and such. Won't get lost in the dust.


Note I am not associated with Macchina, just an interested party.
